environment:
    PSGalleryAPIKey:
        secure: Kffca6TRgAQESKLBk5ghCDMFbMmH2+8DzLyu1M6a7EBRJCwfxaiJeaIXs9SmQz0i
    access_token:
        secure: PX1R0Ds6r3TTm+wxVbx8MRAgjCRV/juO3cYSEz1MedB/OXvZ3YkqpQGE+X47bcFT
    fast_finish: true
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        - APPVEYOR_BUILD_WORKER_IMAGE: WMF 4
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          PowershellVersion: "6.0.0"

version: 0.1.{build}

# Don't rebuild when I tag a release on GitHub
skip_tags: true

# Ignore testing a commit if only the readme changed
# Or if I include "skip-tests" in the commit message
skip_commits:
  message: /skip\-tests/
  files:
    - .github/
    - .vscode/
    - README.md
    - .gitattributes
    - .gitignore
    - .env*

# PRs, by definition, don't change anything and therefore should not increment the version
# To be fair, this is not important, and is really just AppVeyor enabling my pedantry
pull_requests:
  do_not_increment_build_number: true

init:
    - if not defined PowershellVersion (set PowershellVersion=5)
    - git config --global credential.helper store
    - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
    - git config --global user.email "support@atlassianps.org"
    - git config --global user.name "AtlassianPS automation"

install:
    - cmd: git config --global core.autocrlf true
    - cmd: git checkout %APPVEYOR_REPO_BRANCH%
    - cmd: if %PowershellVersion:~0,1% gtr 5 (pwsh -File ./Tools/setup.ps1) else (powershell -File ./Tools/setup.ps1)

before_build:
    - cmd: if %PowershellVersion:~0,1% gtr 5 (pwsh -Command "Invoke-Build -Task ShowDebug") else (powershell -Command "Invoke-Build -Task ShowDebug")

build_script:
    - cmd: if %PowershellVersion:~0,1% gtr 5 (pwsh -Command "Invoke-Build -Task Build") else (powershell -Command "Invoke-Build -Task Build")

test_script:
    - cmd: if %PowershellVersion:~0,1% gtr 5 (pwsh -Command "Invoke-Build -Task Test") else (powershell -Command "Invoke-Build -Task Test")

before_deploy:
    - cmd: if %PowershellVersion:~0,1% gtr 5 (pwsh -Command "Invoke-Build -Task Deploy") else (powershell -Command "Invoke-Build -Task Deploy")

deploy:
    provider: GitHub
    release: v$(appveyor_build_version)
    description: ''
    auth_token:
        secure: PX1R0Ds6r3TTm+wxVbx8MRAgjCRV/juO3cYSEz1MedB/OXvZ3YkqpQGE+X47bcFT
    # artifact: /Release/BitbucketPS.zip
    draft: false
    prerelease: false
    on:
        branch: master                  # release from master branch only
        appveyor_repo_tag: false        # deploy on tag push only

# on_failure:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
